django_ws_2_3/project3/urls.py
from django.contrib import admin
from django.urls import path, include
# from throw_catch import views

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('throw_catch/', include("throw_catch.urls"))
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('throw_catch/', include("throw_catch.urls", namespace="throw_catch")),  # throw_catch 애플리케이션의 URL을 포함합니다.
]

django_ws_2_3/throw_catch/urls.py
from django.urls import path
from . import views

app_name = "throw_catch"
urlpatterns = [
    path('first/', views.first, name='first'),  
    path('second/', views.second, name='second'),  
]

django_ws_2_3/throw_catch/models.py
from django.db import models

# Create your models here.

django_ws_2_3/throw_catch/views.py
from django.shortcuts import render


def first(request):
    message = None  # 초기 출력 화면에 아무것도 받지 못함을 나타내기 위해
    context = {
        'message': message,
    }
    return render(request, 'throw_catch/first.html', context)

def second(request):
    message = request.GET.get('message')
    context = {
        'message': message,
    }
    return render(request, 'throw_catch/second.html', context)

django_ws_2_3/throw_catch/templates/throw_catch/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

django_ws_2_3/throw_catch/templates/throw_catch/first.html
{% extends "throw_catch/base.html" %}

{% block content %}
    {% if message %}
        <p>catch : {{ message }} 을/를 받음!</p>
    {% else %}
        <p>catch : 아무것도 받지 못함</p>
    {% endif %}
    <form action="{% url 'throw_catch:second' %}" method="GET">
        <div class="container">
            <label for="message">throw:</label>
            <input type="text" id="message" name="message">
            <input type="submit" value="휙">
        </div>
    </form>
{% endblock content %}

django_ws_2_3/throw_catch/templates/throw_catch/second.html
{% extends "throw_catch/base.html" %}

{% block content %}
    {% if message %}
        <p>catch : {{ message }} 을/를 받음!</p>
    {% else %}
        <p>catch : 아무것도 받지 못함</p>
    {% endif %}
    <form action="{% url 'throw_catch:first' %}" method="GET">
        <div class="container">
            <label for="message">throw:</label>
            <input type="text" id="message" name="message">
            <input type="submit" value="휙">
        </div>
    </form>
{% endblock content %}